version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
      - ./backups:/app/backups
    environment:
      - FLASK_ENV=development
